spring:
  datasource: 
    url: jdbc:mariadb://localhost:3306/courtcases
    username: root
    password: Garant27
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      
