spring:
  datasource: 
    url: jdbc:mariadb://court:3306/courtcases
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456Aa
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      
